steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', '--single-branch', '--branch', 'main', 'https://github.com/mxbikes-net/pkz-locker']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/pkz-locker', '.']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'pkz-locker', '--image', 'gcr.io/$PROJECT_ID/pkz-locker', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated']

images:
  - 'gcr.io/$PROJECT_ID/pkz-locker'
